feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout:  5000
  news:
    url: ${NEWSHABIT_AUTH_URL:http://localhost:8082}
  internal-access-token: ${INTERNAL_ACCESS_TOKEN}
