spring:
  cloud:
    function:
      definition: refineNews;crawl;sinkRefinedNews;
    stream:
      bindings:
        refineNews-in-0:
          destination: ${CRAWL_TOPIC}
          content-type: application/avro
          group: refine-group
          consumer:
            partitioned: true
            concurrency: 6
            maxAttempts: 3
            back-off-initial-interval: 1000
            use-native-decoding: true

        refineNews-out-0:
          destination: ${REFINED_NEWS_TOPIC}
          content-type: application/avro
          group: refine-group
          producer:
            use-native-encoding: true

        crawl-out-0:
          destination: ${CRAWL_TOPIC}
          content-type: application/avro
          group: crawl-group
          producer:
            use-native-encoding: true

        sinkRefinedNews-in-0:
          destination: ${REFINED_NEWS_TOPIC}
          content-type: application/avro
          group: sink-group
          consumer:
            partitioned: true
            maxAttempts: 3
            back-off-initial-interval: 1000
            use-native-decoding: true
      kafka:
        binder:
          brokers: ${KAFKA_URL}
          auto-create-topics: false
        bindings:
          refineNews-in-0:
            consumer:
              configuration:
                key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: ${SCHEMA_REGISTRY_URL}
                linger.ms: 1000
                specific.avro.reader: true
                max.poll.records: 6

          refineNews-out-0:
            producer:
              configuration:
                key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: ${SCHEMA_REGISTRY_URL}
                linger.ms: 1000
                auto.register.schemas: true
                specific.avro.reader: true

          crawl-out-0:
            producer:
              configuration:
                key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: ${SCHEMA_REGISTRY_URL}
                linger.ms: 1000
                auto.register.schemas: true

          sinkRefinedNews-in-0:
            consumer:
              reset-offsets: true
              start-offset: latest
              configuration:
                key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: ${SCHEMA_REGISTRY_URL}
                linger.ms: 1000
                specific.avro.reader: true
app:
  kafka:
    crawl:
      binding: "crawl-out-0"
