spring:
  cloud:
    stream:
      bindings:
        crawl-out-0:
          destination: ${CRAWL_TOPIC}
          content-type: application/avro
          group: crawl-group
          producer:
            use-native-encoding: true
      kafka:
        binder:
          brokers: localhost:29092
          auto-create-topics: false
        bindings:
          crawl-out-0:
            producer:
              configuration:
                key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: ${SCHEMA_REGISTRY_URL}
                linger.ms: 1000
                auto.register.schemas: true
app:
  kafka:
    crawl:
      binding: ${CRAWL_BINDING}
