server:
  port: 8080

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092,localhost:39092,localhost:49092
          auto-create-topics: false

app:
  kafka:
    crawl:
      topic: crawl
  crawl:
    start-time: 1000
    end-time: 2000

