server:
  port: 8083
  error:
    whitelabel:
      enabled: false
app:
  crawl:
    headline-uri: ${HEADLINE_URI}
    user-agent: ${USER_AGENT}
    cron: ${CRAWL_CRON:0 0 * * * *}
    sleep-min: 1000
    sleep-max: 2000
    start-idx: 1
    end-idx: 10

