server:
  port: 8080
  error:
    whitelabel:
      enabled: false

app:
  crawl:
    headline-uri: ${HEADLINE_URI}
    user-agent: ${USER_AGENT}
    cron: ${CRAWL_CRON:0 0 * * * *}
    sleep-min: 1000
    sleep-max: 2000
    start-idx: 1
    end-idx: 10
  news:
    delete:
      cron: ${NEWS_DELETE_CRON:0 0 2 * * *}
      click_cnt: ${NEWS_DELETE_CLICK_CNT:5}
      date: ${NEWS_DELETE_DATE:14}
