bootJar { enabled = true }

jar { enabled = false }

version="2.0.0"

dependencies {
    implementation project(':common')
    implementation project(":common-event")
    implementation project(":common-auth")
    implementation project(":aiprocess")
    implementation project(":auth")
    implementation project(":crawl")
    implementation project(":news")
    implementation project(":user")

    // jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'
}
