services:
  newshabit-user:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${NEWSHABIT_IMAGE_NAME}:${NEWSHABIT_IMAGE_TAG}
    container_name: newshabit
    cpus: 0.8
    mem_limit: 518M
    restart: on-failure:3
    volumes:
      - /data/user/log:/app/log
      - /data/auth:/data/auth
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - "8085:8085"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx518m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: "app,auth,jdbc,"

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_PROMPT: ${GEMINI_PROMPT}
      HEADLINE_URI: ${HEADLINE_URI}
      USER_AGENT: ${USER_AGENT}
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
      RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
      RDS_URL: ${RDS_URL}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      CRAWL_TOPIC: ${CRAWL_TOPIC}
      REFINED_NEWS_TOPIC: ${REFINED_NEWS_TOPIC}
      KAFKA_URL: ${KAFKA_URL}
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}

    networks:
      - newshabit-3

networks:
  newshabit-3:
    driver: bridge
