bootJar { enabled = false }

jar { enabled = true }

dependencies {
    implementation project(':common')
    implementation project(':common-auth')
    implementation project(':auth')

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation("org.springframework.boot:spring-boot-starter-security")

    //jpa
    implementation'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'
}
