services:
  newshabit-user:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${NEWSHABIT_USER_IMAGE_NAME}:${NEWSHABIT_USER_IMAGE_TAG}
    container_name: newshabit-user
    restart: always
    volumes:
      - /data/user/log:/app/log
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - "8085:8085"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx512m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: "app,auth,jdbc"
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
      RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
      ACCESS_TOKEN_VALID_TIME: ${ACCESS_TOKEN_VALID_TIME}
      REFRESH_TOKEN_VALID_TIME: ${REFRESH_TOKEN_VALID_TIME}
      RDS_URL: ${RDS_URL}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
    networks:
      - newshabit-2

networks:
  newshabit-2:
    driver: bridge
