bootJar { enabled = true }

jar { enabled = false }

version="2.0.0"

dependencies {
    implementation project(':common')
    implementation project(':common-auth')
    implementation project(":common-event")

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation("org.springframework.boot:spring-boot-starter-security")

    // kafka
    implementation 'org.springframework.cloud:spring-cloud-stream'
    implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.cloud:spring-cloud-stream-test-binder'

    // crawl
    implementation 'org.jsoup:jsoup:1.15.4'

    // avro
    implementation('org.apache.avro:avro:1.11.4')
    implementation("io.confluent:kafka-avro-serializer:7.8.0")
}
