services:
  newshabit-crawl:
    build:
      context: ..
      dockerfile: crawl/Dockerfile
    image: ${NEWSHABIT_CRAWL_IMAGE_NAME}:${NEWSHABIT_CRAWL_IMAGE_TAG}
    container_name: newshabit-crawl
    cpus: 0.125
    mem_limit: 256M
    restart: on-failure:3
    volumes:
      - /data/crawl/log:/app/log
      - /data/auth/rsa:/data/auth/rsa
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - "8083:8083"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx128m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: "app,auth,spring-cloud-stream"
      HEADLINE_URI: ${HEADLINE_URI}
      USER_AGENT: ${USER_AGENT}
      ACCESS_TOKEN_VALID_TIME: ${ACCESS_TOKEN_VALID_TIME}
      REFRESH_TOKEN_VALID_TIME: ${REFRESH_TOKEN_VALID_TIME}
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
      RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
      CRAWL_TOPIC: ${CRAWL_TOPIC}
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      KAFKA_URL: ${KAFKA_URL}
    networks:
      - newshabit-2

networks:
  newshabit-2:
    driver: bridge
